### ISSUE TITLE
github actions to push docker image to docker hub 

### ISSUE THREAD

**Issue by DiptoChakrabarty** [DiptoChakrabarty/api#2]
Self Explanatory

**Comment by kentwongg** [comment]
I'll give this a try.

**Comment by DiptoChakrabarty** [comment]
> I'll give this a try.

Sure @kentwongg  please go ahead

**Comment by kentwongg** [comment]
Hi @DiptoChakrabarty I got it working and tested it. It successfully builds and pushes a docker image to my docker hub upon release.

Let me know if there's anything to fix:

-I made the workflow yml
-default location in FlaskKube-api/.github/workflows/docker-publish.yml
-It only triggers on release (not sure if you want this or after every commit?)
-Uses github secrets for the credentials and hardcode the docker hub name and repo in the yaml

Let me know if that's okay and I'll create the pull request!

**Comment by DiptoChakrabarty** [comment]
> Hi @DiptoChakrabarty I got it working and tested it. It successfully builds and pushes a docker image to my docker hub upon release.
> 
> Let me know if there's anything to fix:
> 
> -I made the workflow yml
> -default location in FlaskKube-api/.github/workflows/docker-publish.yml
> -It only triggers on release (not sure if you want this or after every commit?)
> -Uses github secrets for the credentials and hardcode the docker hub name and repo in the yaml
> 
> Let me know if that's okay and I'll create the pull request!

Yes this sounds good , could you just change the trigger for every commit

**Comment by kentwongg** [comment]
@DiptoChakrabarty Alright, I've created the PR.

**Comment by DiptoChakrabarty** [comment]
> @DiptoChakrabarty Alright, I've created the PR.

Yes merged it , working perfectly thanks
