### ISSUE TITLE
Add Postman API docs in Readme

### ISSUE THREAD

**Issue by DiptoChakrabarty** [DiptoChakrabarty/api#3]
Right now the api routes are hard coded in the Readme , it would be better if postman api docs were added to the ReadME

**Comment by ShubhamPalriwala** [comment]
Can I resolve the issue ?
For reference, are you looking for something like the one I made a while ago:
https://documenter.getpostman.com/view/11026000/Szzhddp3?version=latest

**Comment by DiptoChakrabarty** [comment]
> Can I resolve the issue ?
> For reference, are you looking for something like the one I made a while ago:
> https://documenter.getpostman.com/view/11026000/Szzhddp3?version=latest

Yes @ShubhamPalriwala this is the one

**Comment by ShubhamPalriwala** [comment]
Alright, I'll do this !

**Comment by viveksahu26** [comment]
Hey @DiptoChakrabarty , is this work for first time user or new contributer. Then i would like to work on it..

**Comment by DiptoChakrabarty** [comment]
> Hey @DiptoChakrabarty , is this work for first time user or new contributer. Then i would like to work on it..

Yes it is open but @ShubhamPalriwala  is has taken up this issue for now

**Comment by ShubhamPalriwala** [comment]
Hey, I am unable to generate all but one request due to unauthorization !
I created a user too but still I dont get a JWT token back in Postman.

**Comment by DiptoChakrabarty** [comment]
After creating a user you have to login with the user at the /auth endpoint to receive a token . I had not given those endpoints in the readme earlier I have added them now

**Comment by ShubhamPalriwala** [comment]
Please close the issue after approving and merging the PR #5

**Comment by DiptoChakrabarty** [comment]
Thanks for sending the PR
